name: RepairPriceEstimator
options:
  bundleIdPrefix: com.jewelryrepair
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: "15.0"

packages: {}

targets:
  RepairPriceEstimator:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: RepairPriceEstimator
        excludes:
          - "**/*.md"
          - "**/ReferenceDocuments/**"
    resources:
      - path: RepairPriceEstimator/Resources
        type: resource
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jewelryrepair.RepairPriceEstimator
        PRODUCT_NAME: RepairPriceEstimator
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        TARGETED_DEVICE_FAMILY: "1" # iPhone
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_CFBundleShortVersionString: "1.0.0"
        INFOPLIST_KEY_CFBundleVersion: "1"
        INFOPLIST_KEY_UIApplicationSupportsMultipleScenes: YES
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        CODE_SIGN_ENTITLEMENTS: RepairPriceEstimator.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_OPTIMIZATION_LEVEL: -Onone
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          DEBUG_INFORMATION_FORMAT: dwarf
        Release:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""
          SWIFT_OPTIMIZATION_LEVEL: -O
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
          ASSETCATALOG_COMPILER_OPTIMIZATION: time
    scheme:
      testTargets:
        - RepairPriceEstimatorTests

  RepairPriceEstimatorTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: RepairPriceEstimatorTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jewelryrepair.RepairPriceEstimatorTests
        PRODUCT_NAME: RepairPriceEstimatorTests
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    dependencies:
      - target: RepairPriceEstimator

schemes:
  RepairPriceEstimator:
    build:
      targets:
        RepairPriceEstimator: all
    test:
      targets:
        - RepairPriceEstimatorTests
    run:
      config: Debug
    archive:
      config: Release

